// <auto-generated />
using Bookoria.DataAcess.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Bookoria.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250503043044_addproduct")]
    partial class addproduct
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Bookoria.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayOrder = 1,
                            Name = "Business"
                        },
                        new
                        {
                            Id = 2,
                            DisplayOrder = 2,
                            Name = "Technology"
                        },
                        new
                        {
                            Id = 3,
                            DisplayOrder = 3,
                            Name = "Adventure"
                        },
                        new
                        {
                            Id = 4,
                            DisplayOrder = 4,
                            Name = "Fictional"
                        });
                });

            modelBuilder.Entity("Bookoria.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("ListPrice")
                        .HasColumnType("float");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<double>("Price100")
                        .HasColumnType("float");

                    b.Property<double>("Price50")
                        .HasColumnType("float");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "John Doe",
                            Description = "A complete guide to ASP.NET Core.",
                            ISBN = "1234567890",
                            ListPrice = 50.0,
                            Price = 45.0,
                            Price100 = 35.0,
                            Price50 = 40.0,
                            Title = "ASP.NET Core Guide"
                        },
                        new
                        {
                            Id = 2,
                            Author = "Jane Smith",
                            Description = "Master Linq with examples.",
                            ISBN = "0987654321",
                            ListPrice = 60.0,
                            Price = 55.0,
                            Price100 = 45.0,
                            Price50 = 50.0,
                            Title = "Linq Mastery"
                        },
                        new
                        {
                            Id = 3,
                            Author = "Jane Smith",
                            Description = "Master Linq with examples.",
                            ISBN = "0987654321",
                            ListPrice = 60.0,
                            Price = 55.0,
                            Price100 = 45.0,
                            Price50 = 50.0,
                            Title = "mvc"
                        },
                        new
                        {
                            Id = 4,
                            Author = "Jane Smith",
                            Description = "LINQ with examples.",
                            ISBN = "0987654321",
                            ListPrice = 60.0,
                            Price = 55.0,
                            Price100 = 45.0,
                            Price50 = 50.0,
                            Title = "Linq Mastery"
                        },
                        new
                        {
                            Id = 5,
                            Author = "Jane Smith",
                            Description = "Master Entity Framework with examples.",
                            ISBN = "0987654321",
                            ListPrice = 60.0,
                            Price = 55.0,
                            Price100 = 45.0,
                            Price50 = 50.0,
                            Title = "Entity Framework Mastery"
                        },
                        new
                        {
                            Id = 6,
                            Author = "Jane Smith",
                            Description = "Master Entity Framework with examples.",
                            ISBN = "0987654321",
                            ListPrice = 60.0,
                            Price = 55.0,
                            Price100 = 45.0,
                            Price50 = 50.0,
                            Title = "Entity Framework Mastery"
                        },
                        new
                        {
                            Id = 7,
                            Author = "Jane Smith",
                            Description = "Master Entity Framework with examples.",
                            ISBN = "0987654321",
                            ListPrice = 60.0,
                            Price = 55.0,
                            Price100 = 45.0,
                            Price50 = 50.0,
                            Title = "Entity Framework Mastery"
                        },
                        new
                        {
                            Id = 8,
                            Author = "Jane Smith",
                            Description = "Master Entity Framework with examples.",
                            ISBN = "0987654321",
                            ListPrice = 60.0,
                            Price = 55.0,
                            Price100 = 45.0,
                            Price50 = 50.0,
                            Title = "Entity Framework Mastery"
                        },
                        new
                        {
                            Id = 9,
                            Author = "Jane Smith",
                            Description = "Master Entity Framework with examples.",
                            ISBN = "0987654321",
                            ListPrice = 60.0,
                            Price = 55.0,
                            Price100 = 45.0,
                            Price50 = 50.0,
                            Title = "Entity Framework Mastery"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
